name: deploy nodeServer

on: 
  push:
    branches:
      - 'main' #针对main分支
    path:
      - '.github/workflows/*'
      - 'servers/**'
      - 'package.json'

jobs:
  deploy:
    runs-on: ubuntu-latest #分配临时服务器 用完会回收

    steps:
      - uses: actions/checkout@v2 #第三方的 action 帮我们拉git仓库的所有代码

      - name: create a folder #创建文件夹
        run: mkdir test-folder
      
      - name: create a file #创建一个文件
        run: |
          cd test-folder
          touch a.txt
          echo "hello" > a.txt
          cat a.txt
        
      - name: delete a file #删除文件
        run: rm -rf a.txt
